std = "lua51"
unused_args = false
unused_secondaries = false
allow_defined_top = true
max_line_length = false
ignore = {
   "611",
   "612",
   "614",
}
exclude_files = {
   "Libs/**",
}

files["**/*.lua"] = {
   globals = {
      "MedaDebugDB",
      "MedaDebugLog",
      "MedaDebugErrors",
      "SLASH_MEDADEBUG1",
      "SLASH_MEDADEBUG2",
      "SLASH_MEDADEBUGERRORS1",
      "SELECTED",
      "INSPECTED",
      "LAST",
      _G = {other_fields = true},
      SlashCmdList = {read_only = false, other_fields = true},
      StaticPopupDialogs = {read_only = false, other_fields = true},
      C_Timer = {
         other_fields = true,
         fields = {
            After = {read_only = false},
            NewTimer = {read_only = false},
            NewTicker = {read_only = false},
         },
      },
   },

   read_globals = {
      "_G",
      "ADDON_LOADED",
      "BackdropTemplate",
      "BasicScriptErrors",
      "BugGrabber",
      "C_AddOns",
      "C_ChallengeMode",
      "C_ChatInfo",
      "C_Map",
      "C_PvP",
      "C_RestrictedActions",
      "C_Secrets",
      "C_Spell",
      "C_TooltipInfo",
      "C_Timer",
      "C_UnitAuras",
      "CopyTable",
      "CreateFrame",
      "EnumerateFrames",
      "Enum",
      "GameFontNormal",
      "GameFontNormalLarge",
      "GameFontNormalSmall",
      "GameTooltip",
      "GetAddOnMemoryUsage",
      "GetBuildInfo",
      "GetCursorPosition",
      "GetFramerate",
      "GetInstanceInfo",
      "GetObjectType",
      "GetNetStats",
      "GetNumGroupMembers",
      "GetNumSubgroupMembers",
      "GetScreenHeight",
      "GetScreenWidth",
      "GetTime",
      "InCombatLockdown",
      "IsInGroup",
      "IsInInstance",
      "IsInRaid",
      "LibStub",
      "ReloadUI",
      "ResetCursor",
      "SelectColor",
      "ScriptErrorsFrame",
      "SetCursor",
      "SlashCmdList",
      "StaticPopupDialogs",
      "StaticPopup_Hide",
      "StaticPopup_Show",
      "UIParent",
      "UISpecialFrames",
      "UnitExists",
      "UnitGUID",
      "UnitName",
      "UnitReaction",
      "UpdateAddOnMemoryUsage",
      "WorldFrame",
      "canaccessvalue",
      "canaccesstable",
      "collectgarbage",
      "date",
      "debugstack",
      "format",
      "geterrorhandler",
      "hasanysecretvalues",
      "issecretvalue",
      "issecrettable",
      "loadstring",
      "print",
      "seterrorhandler",
      "strmatch",
      "strsplit",
      "strupper",
      "time",
      "tinsert",
      "tremove",
      "unpack",
      "wipe",
   },
}
